project:
  type: website

website:
  title: Sina Atalay
  description: "My personal website, which contains posts about the engineering projects I have worked on."
  site-url: https://sinaatalay.com
  google-analytics: G-HH8XZL6SQK
  favicon: images/favicon.png

  open-graph:
    site-name: Sina Atalay
    locale: en_US

  search:
    type: overlay
    location: navbar

  navbar:
    title: false
    collapse: false
    left:
      - text: Posts
        href: index.qmd
      - icon: github
        href: https://github.com/sinaatalay
      - icon: linkedin
        href: https://www.linkedin.com/in/sinaatalay/
  page-footer: Copyright © 2023 Sina Atalay
format:
  html:
    theme: default
    link-external-icon: true
    css: styles.css
    html-math-method: katex

page-layout: article
resources:
  - CNAME
